// Code generated by "stringer -type=Gundam"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RX78-0]
	_ = x[zeta-1]
	_ = x[zz-2]
}

const _Gundam_name = "RX78zetazz"

var _Gundam_index = [...]uint8{0, 4, 8, 10}

func (i Gundam) String() string {
	if i < 0 || i >= Gundam(len(_Gundam_index)-1) {
		return "Gundam(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Gundam_name[_Gundam_index[i]:_Gundam_index[i+1]]
}
